server:
  port: 8100
spring:
  application:
    name: ananops-provider-mdmc
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    date-format: yyyy-MM-dd HH:mm:ss
  cache:
    cache-names: mdm-cache
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ananops_mdmc?characterEncoding=utf8&useSSL=false&serverTimezone=GMT
    username: root
    password: 123456
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql